name: Build and publish resume

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-publish:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build resume
        run: npm run build 
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.INTELLIS_DEPLOYER_ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.INTELLIS_DEPLOYER_SECRETACCESSKEY }}
          aws-region: ap-southeast-2
      
      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: /home/runner/work/resume/resume/out
          bucket: matt.tew.io/resume
          bucket-region: ap-southeast-2
          dist-id: EHETIWCRJ7W6U
          invalidation: /resume/*